# Generated by Django 4.0.3 on 2022-03-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_basetable_pmc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetable',
            name='BC',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='basetable',
            name='PMC',
            field=models.CharField(blank=True, default='NA', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='basetable',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basetable',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basetable',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
