# Generated by Django 4.0.3 on 2022-03-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_basetable_bc_alter_basetable_pmc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetable',
            name='PMC',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
