# Generated by Django 4.0.3 on 2022-04-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_basetable_pr_basetable_prdate_basetable_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basetable',
            old_name='Project',
            new_name='project',
        ),
    ]
