# Generated by Django 4.0.3 on 2022-04-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_project_table_vendor_table_alter_basetable_project_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basetable',
            table='maindb',
        ),
    ]
