# Generated by Django 4.0.3 on 2022-05-06 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_basetable_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetable',
            name='PO',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
