# Generated by Django 4.0.3 on 2022-05-07 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_basetable_bc1_alter_basetable_bc2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='expired_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO', models.CharField(max_length=20)),
                ('oldPO', models.CharField(blank=True, max_length=20, null=True)),
                ('typePO', models.CharField(blank=True, max_length=20, null=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('PR', models.CharField(blank=True, max_length=20, null=True)),
                ('PRdate', models.DateField(blank=True, null=True)),
                ('BC1', models.BooleanField(default=False, null=True)),
                ('BC2', models.BooleanField(default=False, null=True)),
                ('BC3', models.BooleanField(default=False, null=True)),
                ('BC4', models.BooleanField(default=False, null=True)),
                ('PMC1', models.BooleanField(default=False, null=True)),
                ('PMC2', models.BooleanField(default=False, null=True)),
                ('PMC3', models.BooleanField(default=False, null=True)),
                ('PMC4', models.BooleanField(default=False, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project_table')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vendor_table')),
            ],
            options={
                'db_table': 'expireddb',
            },
        ),
    ]
