# Generated by Django 4.0.3 on 2022-05-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_expired_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expired_table',
            name='PO',
            field=models.CharField(help_text='This is compulsory', max_length=20),
        ),
    ]
